name: videoalignment
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - ffmpeg=4.1.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - lame=3.100
  - libiconv=1.15
  - nettle=3.4.1
  - openh264=1.8.0
  - openssl=1.1.1b
  - x264=1!152.20180806
  - blas=1.0
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - freetype=2.9.1
  - intel-openmp=2019.3
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - pillow=6.0.0
  - pip=19.1
  - pycparser=2.19
  - python=3.6.8
  - readline=7.0
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.1.0
  - torchvision=0.2.2
  - pip:
      - imageio==2.5.0
      - imageio-ffmpeg==0.3.0
      - progressbar==2.5
